{{- range $key, $config := .Values.myConfigMaps }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  # Name is constructed dynamically (e.g., inventory-app-db-config)
  name: {{ $.Values.fullname }}-{{ $config.suffix }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
data:
  # Loop through the data map and quote every value automatically
  {{- range $dataKey, $dataValue := $config.data }}
  {{ $dataKey }}: {{ $dataValue | quote }}
  {{- end }}
{{- end }}
{{- end }}