{{- range $key, $config := .Values.myConfigMaps }} # Iterate over configMaps defined in values.yaml
{{- if $config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-app.fullname" $ }}-{{ $config.suffix }}
  labels:
    {{- include "inventory-app.labels" $ | nindent 4 }}
data:
  # Loop through the data map and quote every value automatically
  {{- range $dataKey, $dataValue := $config.data }} # Iterate over data entries
  {{ $dataKey }}: {{ $dataValue | quote }} # datakey: "datavalue"
  {{- end }}
{{- end }}
{{- end }}