{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "inventory-app.fullname" . }}-statefulset
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
spec:

  serviceName: {{ .Values.myServices.postgres.name | quote }}
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.myServices.postgres.selector | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inventory-app.labels" . | nindent 8 }}
        {{- toYaml .Values.myServices.postgres.selector | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.postgresql.containerName | default "postgres" }}
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER #hardcoded due to software inside the container is hard-coded to look for this specific value
          valueFrom:
            configMapKeyRef:
              name: {{ include "inventory-app.fullname" . }}-db-config
              key: postgres-user
        - name: POSTGRES_PASSWORD #These keys represent the connection between your configmap.yaml and your statefulset.yaml.
          valueFrom:
            secretKeyRef:
              name: {{ include "inventory-app.fullname" . }}-db-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ include "inventory-app.fullname" . }}-db-config
              key: postgres-db
                
        volumeMounts:
        - name: postgres-storage
          mountPath: {{ .Values.postgresql.mountPath }}
          
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ {{ .Values.postgresql.storage.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.postgresql.storage.size }}
{{- end }}