{{- if .Values.common.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  # Replaced helper with direct value
  name: {{ .Values.fullname }}-secret
  labels:
    # Replaced helper with toYaml
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
{{- end -}}