# create a secret.yaml file for each value file

# --- SECRET FOR DATABASE RELEASE ---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}-db-secret
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Only DB Password goes here
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
{{- end }}

# --- SECRET FOR APP RELEASE ---
{{- if .Values.app.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}-app-secret
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Only Admin Password goes here
  admin-password: {{ .Values.secrets.adminPassword | quote }}
---
{{- end }}