# --- SECRET FOR DATABASE RELEASE ---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  # Name ends in '-db-secret'
  name: {{ .Values.fullname }}-db-secret
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
stringData:
  # Only DB Password goes here
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
{{- end }}

# --- SECRET FOR APP RELEASE ---
{{- if .Values.app.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  # Name ends in '-app-secret'
  name: {{ .Values.fullname }}-app-secret
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
stringData:
  # Only Admin Password goes here
  admin-password: {{ .Values.secrets.adminPassword | quote }}
---
{{- end }}