# --- GLOBAL SETTINGS ---
fullname: inventory-app

postgresql:
  enabled: false

common:
  enabled: false  

labels:
  app: inventory-app
  tier: backend
  owner: "devops-team"

selectorLabels:
  app: inventory-app
  tier: backend

# --- APPLICATION CONFIGURATION ---
app:
  enabled: true
  replicaCount: 5
  containerPort: 8000  ## CANNOT EDIT

image:
  repository: ravindukuruppuarachchi/inventory_project_api
  tag: "multistage"
  pullPolicy: IfNotPresent

# --- SERVICES (Map Format) ---
myServices:
  # Disable postgres service for App release
  postgres:
    enabled: false

  backend:
    name: inventory-service
    enabled: true
    type: LoadBalancer
    #nodePort: 30007
    port: 8000 # EDITABLE: This is the internal Service IP port
    targetPort: 8000 # CANNOT EDIT: Must match 'app.containerPort' above
    selector:
      app: inventory-app
      tier: backend

# --- APP CONFIG & SECRETS ---
myConfigMaps:
  # Enable App Config
  app:
    enabled: true
    suffix: "app-config"
    data:
      admin-email: "admin@airarabia.com"
      database-url: "postgresql://postgres:airarabia@postgres-service:5432/inventory_db"

      #removed database-url as db password is not here anymore

  # Disable DB Config
  db:
    enabled: false


secrets:
  adminPassword: "SecretAdminPassword123!" # Injected via Jenkinsfile

# --- ADDITIONAL APP RESOURCES ---
serviceAccount:
  create: true
  name: "inventory-sa"
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50


livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi