apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: inventory_project_api:multistage  # <--- MUST MATCH YOUR LOCAL IMAGE
        imagePullPolicy: Never  # <--- IMPORTANT: Tells K8s to use local image
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database-url
        - name: ADMIN_EMAIL
          value: "admin@airarabia.com"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: admin-password
