apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Kubernetes will encode these for you automatically
  postgres-password: "airarabia"
  admin-password: "SecretAdminPassword123!"
