---
# remove internal firewall of the instnance
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Flush existing firewall rules (sudo iptables -F)
  ansible.builtin.iptables:
    flush: yes
  # This deletes all internal blocking rules immediately.

- name: Save firewall rules to be persistent
  command: netfilter-persistent save
  # make sure the changes are persistant

# By default, Postgres only listens to "localhost". We must tell it to listen to the public network card so it can hear my laptop.
- name: Allow remote connections in postgresql.conf
  lineinfile:  # Searches for a line in a text file and replaces it
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses" # Look for a line that starts with 'listen_addresses',
    line: "listen_addresses = '*'" # change it from localhost to *
  notify: Restart Postgres


# 2. CONFIGURE WHITELIST (The Bouncer)
- name: Add Trusted IPs to whitelist
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    line: "host    all             all             {{ item }}    scram-sha-256"
    state: present
  loop: "{{ trusted_ips }}"
  notify: Restart Postgres

#the "Client Authentication" (HBA) file typically blocks strangers
- name: Allow password auth in pg_hba.conf
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"

    # The Rule Breakdown:
    # host          = Connect via network (TCP/IP)
    # all           = Allow access to ALL databases
    # all           = Allow access to ALL users
    # 0.0.0.0/0     = Allow requests from ANY IP address in the world
    # scram-sha-256 = Require a secure password login

    line: "host    all             all             0.0.0.0/0            scram-sha-256"
    state: absent  # Ensure this insecure rule is NOT present
  notify: Restart Postgres


  


